//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_that_have_been_in_the_system_today
    {
        public string Username { get; set; }
        public System.DateTime LastLogin { get; set; }
    }
}
